[project]
name = "AIAmplitudes"
version = "0.0.2"
authors = [
  { name="Garrett Merz", email="garrett.merz@wisc.edu" },
  { name="Francois Charton", email="fcharton@meta.com" },
  { name="Tianji Cai", email="tianjiresearch@gmail.com" },
  { name="Kyle Cranmer", email="kscranmer@wisc.edu" },
  { name="Matthias Wilhelm", email="mailmwilhelm@imada.sdu.dk" },
  { name="Lance Dixon", email="lance@slac.stanford.edu" },
]
description = "A library of common utils for the AI Amplitudes project"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

dependencies=[
'wandb',
'pillow',
'tensorboard',
'pandas',
'numpy',
'wraps',
'partial',
'matplotlib',
'sympy',
'ipython',
'torch==2.5.1',
'torchmetrics==1.6.0',
'scipy',
'einops'
]


[project.urls]
Homepage = "https://github.com/AIAmplitudes"
